<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <NeutralLanguage>en-US</NeutralLanguage>
    <LangVersion>13.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <OutputPath>../../Bin/$(Configuration)/</OutputPath>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ILGPUC.CompilerService.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ILGPU\ILGPU.csproj" />
    <ProjectReference Include="..\ILGPUC.Compilers\ILGPUC.Compilers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0-*" />
  </ItemGroup>

</Project>
