// ---------------------------------------------------------------------------------------
//                                        ILGPU
//                           Copyright (c) 2025 ILGPU Project
//                                    www.ilgpu.net
//
// File: DispatchStubGenerator.cs
//
// This file is part of ILGPU and is distributed under the University of Illinois Open
// Source License. See LICENSE.txt for details.
// ---------------------------------------------------------------------------------------

using ILGPUC.Roslyn.Analysis;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ILGPUC.Roslyn.Generation;

/// <summary>
/// Generates a static dispatch class for a monomorphized generic kernel.
/// The dispatch class has a generic <c>Launch</c> method that matches on
/// <c>typeof()</c> to forward to the correct concrete compiled kernel class.
/// The JIT constant-folds the <c>typeof(T) == typeof(int)</c> checks to
/// zero-overhead dispatch.
/// </summary>
static class DispatchStubGenerator
{
    /// <summary>
    /// Generates a dispatch stub that routes generic Launch calls to
    /// concrete compiled kernel Launch methods via typeof() matching.
    /// </summary>
    /// <param name="original">
    /// The original open-generic kernel descriptor.
    /// </param>
    /// <param name="specializations">
    /// The concrete specialization descriptors (with mangled names).
    /// </param>
    /// <returns>C# source text for the dispatch stub class.</returns>
    public static string GenerateDispatchStub(
        KernelDescriptor original,
        List<KernelDescriptor> specializations)
    {
        var sb = new StringBuilder(4 * 1024);
        sb.AppendLine("// Generated by ILGPU Roslyn Frontend — Dispatch Stub");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using ILGPU;");
        sb.AppendLine("using ILGPU.Runtime;");
        sb.AppendLine();
        sb.AppendLine(
            $"internal static class {original.KernelName}_CompiledKernel");
        sb.AppendLine("{");

        // Build generic type parameter list and where constraints
        var gm = original.KernelMethod!;
        var typeParams = gm.TypeArguments
            .OfType<ITypeParameterSymbol>()
            .ToArray();

        var genericSuffix = $"<{string.Join(", ", typeParams.Select(t => t.Name))}>";
        var whereClause = BuildWhereConstraints(typeParams);

        // Build parameter list
        sb.Append($"    internal static void Launch{genericSuffix}(");
        sb.AppendLine();
        sb.AppendLine("        AcceleratorStream stream,");
        sb.AppendLine("        KernelConfig config,");

        // Determine dimension params
        int indexDims = original.Variant switch
        {
            LaunchVariant.Auto2D or LaunchVariant.AutoLong2D
                or LaunchVariant.Auto2DStride
                or LaunchVariant.AutoLong2DStride => 2,
            LaunchVariant.Auto3D or LaunchVariant.AutoLong3D
                or LaunchVariant.Auto3DStride
                or LaunchVariant.AutoLong3DStride => 3,
            _ => 1
        };

        sb.Append("        long userExtent");
        for (int d = 0; d < indexDims && indexDims > 1; d++)
        {
            var dimName = d switch { 0 => "_dimX", 1 => "_dimY", _ => "_dimZ" };
            sb.Append($",\n        int {dimName}");
        }

        if (original.Parameters.Length == 0)
        {
            sb.AppendLine(")");
        }
        else
        {
            sb.AppendLine(",");
            for (int i = 0; i < original.Parameters.Length; i++)
            {
                var param = original.Parameters[i];
                var suffix = i < original.Parameters.Length - 1 ? "," : ")";
                sb.AppendLine(
                    $"        {LauncherStubGenerator.FormatTypeNamePublic(param.Type)} " +
                    $"{param.Name}{suffix}");
            }
        }

        if (whereClause.Length > 0)
            sb.Append(whereClause);
        sb.AppendLine("    {");

        // Generate typeof() dispatch branches
        var typeParamSet = new HashSet<ITypeParameterSymbol>(
            typeParams, SymbolEqualityComparer.Default);

        foreach (var spec in specializations)
        {
            if (spec.ConcreteTypeArgs is null)
                continue;

            var concreteArgs = spec.ConcreteTypeArgs.Value;

            // Build condition: typeof(T) == typeof(int) && typeof(TOp) == typeof(AdditionOp)
            var conditions = new List<string>();
            for (int i = 0; i < typeParams.Length && i < concreteArgs.Length; i++)
            {
                var concreteTypeName =
                    LauncherStubGenerator.FormatTypeNamePublic(concreteArgs[i]);
                conditions.Add(
                    $"typeof({typeParams[i].Name}) == typeof({concreteTypeName})");
            }

            sb.AppendLine(
                $"        if ({string.Join("\n            && ", conditions)})");
            sb.AppendLine("        {");

            // Build the forwarding call
            sb.Append(
                $"            {spec.KernelName}_CompiledKernel.Launch(");
            sb.AppendLine();
            sb.Append("                stream, config, userExtent");

            // Add dimension args if multi-dim
            for (int d = 0; d < indexDims && indexDims > 1; d++)
            {
                var dimName = d switch { 0 => "_dimX", 1 => "_dimY", _ => "_dimZ" };
                sb.Append($", {dimName}");
            }

            // Forward parameters, adding Unsafe.As casts where needed
            for (int i = 0; i < original.Parameters.Length; i++)
            {
                var param = original.Parameters[i];
                var concreteParam = spec.Parameters[i];
                sb.AppendLine(",");

                if (ContainsTypeParameter(param.Type, typeParamSet))
                {
                    var fromType =
                        LauncherStubGenerator.FormatTypeNamePublic(param.Type);
                    var toType =
                        LauncherStubGenerator.FormatTypeNamePublic(concreteParam.Type);
                    sb.Append(
                        $"                Unsafe.As<{fromType}, {toType}>" +
                        $"(ref {param.Name})");
                }
                else
                {
                    sb.Append($"                {param.Name}");
                }
            }

            sb.AppendLine(");");
            sb.AppendLine("            return;");
            sb.AppendLine("        }");
        }

        // Fallback: throw for unknown specializations
        sb.AppendLine(
            $"        throw new NotSupportedException(");
        var typeArgNames = string.Join(
            ", ",
            typeParams.Select(t => $"{{typeof({t.Name}).Name}}"));
        sb.AppendLine(
            $"            $\"No compiled kernel for " +
            $"{original.KernelName}<{typeArgNames}>\");");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Builds <c>where</c> constraint clauses for the given type parameters.
    /// </summary>
    private static string BuildWhereConstraints(
        ITypeParameterSymbol[] typeParams)
    {
        var constraints = new StringBuilder();
        foreach (var tp in typeParams)
        {
            var parts = new List<string>();
            if (tp.HasUnmanagedTypeConstraint)
                parts.Add("unmanaged");
            else if (tp.HasValueTypeConstraint)
                parts.Add("struct");
            else if (tp.HasReferenceTypeConstraint)
                parts.Add("class");
            foreach (var ct in tp.ConstraintTypes)
                parts.Add(FormatConstraintType(ct));
            if (tp.HasConstructorConstraint && !tp.HasValueTypeConstraint)
                parts.Add("new()");
            if (parts.Count > 0)
                constraints.AppendLine(
                    $"        where {tp.Name} : {string.Join(", ", parts)}");
        }
        return constraints.ToString();
    }

    /// <summary>
    /// Formats a constraint type using fully-qualified names.
    /// </summary>
    private static string FormatConstraintType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.IsGenericType)
        {
            var baseName = named.OriginalDefinition
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", "", StringComparison.Ordinal);
            var angleIdx = baseName.IndexOf('<');
            if (angleIdx >= 0)
                baseName = baseName[..angleIdx];
            var typeArgs = string.Join(", ",
                named.TypeArguments.Select(
                    LauncherStubGenerator.FormatTypeNamePublic));
            return $"{baseName}<{typeArgs}>";
        }

        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                   .Replace("global::", "", StringComparison.Ordinal);
    }

    /// <summary>
    /// Returns <see langword="true"/> if the given type transitively contains
    /// any of the specified type parameters (e.g., <c>ArrayView1D&lt;T, S&gt;</c>
    /// contains type param <c>T</c>).
    /// </summary>
    private static bool ContainsTypeParameter(
        ITypeSymbol type,
        HashSet<ITypeParameterSymbol> typeParams)
    {
        if (type is ITypeParameterSymbol tp)
            return typeParams.Contains(tp);

        if (type is INamedTypeSymbol named && named.IsGenericType)
        {
            foreach (var arg in named.TypeArguments)
            {
                if (ContainsTypeParameter(arg, typeParams))
                    return true;
            }
        }

        return false;
    }
}
