// ---------------------------------------------------------------------------------------
//                                        ILGPU
//                           Copyright (c) 2026 ILGPU Project
//                                    www.ilgpu.net
//
// File: LauncherStubGenerator.cs
//
// This file is part of ILGPU and is distributed under the University of Illinois Open
// Source License. See LICENSE.txt for details.
// ---------------------------------------------------------------------------------------

using ILGPUC.Roslyn.Analysis;
using Microsoft.CodeAnalysis;
using System;
using System.Linq;
using System.Text;

namespace ILGPUC.Roslyn.Generation;

/// <summary>
/// Generates CompiledKernel stub classes for each kernel.
/// These stubs provide the Launch method signature so rewritten user code compiles.
/// The real implementation is provided by ILGPUC's backend codegen.
/// </summary>
static class LauncherStubGenerator
{
    /// <summary>
    /// Generates a stub C# source string for a <c>*_CompiledKernel</c> class.
    /// The generated class exposes a <c>Launch</c> static method with the correct
    /// parameter types; the method body throws <see cref="NotSupportedException"/>
    /// and is replaced by the real ILGPUC-compiled implementation at build time.
    /// </summary>
    /// <param name="kernel">The kernel descriptor to generate a stub for.</param>
    /// <returns>C# source text for the stub class.</returns>
    public static string GenerateStub(KernelDescriptor kernel)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by ILGPU Roslyn Frontend");
        sb.AppendLine("using System;");
        sb.AppendLine("using ILGPU;");
        sb.AppendLine("using ILGPU.Runtime;");
        sb.AppendLine();
        sb.AppendLine($"internal static class {kernel.KernelName}_CompiledKernel");
        sb.AppendLine("{");

        // Build generic type parameter list for generic kernel methods.
        // Only when type arguments are still unresolved type parameters
        // (e.g. <T, TOp> from a generic caller), not concrete types
        // (e.g. <LambdaClosure, long>).
        var genericSuffix = "";
        var whereClause = "";
        if (kernel.KernelMethod is { IsGenericMethod: true } gm
            && gm.TypeArguments.Any(t => t is ITypeParameterSymbol))
        {
            var typeParams = gm.TypeArguments
                .Select(t => FormatTypeName(t))
                .ToArray();
            genericSuffix = $"<{string.Join(", ", typeParams)}>";

            // Emit where constraints
            var constraints = new StringBuilder();
            foreach (var tp in gm.TypeArguments.OfType<ITypeParameterSymbol>())
            {
                var parts = new System.Collections.Generic.List<string>();
                if (tp.HasUnmanagedTypeConstraint)
                    parts.Add("unmanaged");
                else if (tp.HasValueTypeConstraint)
                    parts.Add("struct");
                else if (tp.HasReferenceTypeConstraint)
                    parts.Add("class");
                foreach (var ct in tp.ConstraintTypes)
                    parts.Add(FormatTypeNameFull(ct));
                if (tp.HasConstructorConstraint && !tp.HasValueTypeConstraint)
                    parts.Add("new()");
                if (parts.Count > 0)
                    constraints.AppendLine(
                        $"        where {tp.Name} : {string.Join(", ", parts)}");
            }
            whereClause = constraints.ToString();
        }

        sb.AppendLine($"    internal static void Launch{genericSuffix}(");
        sb.AppendLine("        AcceleratorStream stream,");

        // Determine dimension params for multi-dim launches
        int indexDims = kernel.Variant switch
        {
            LaunchVariant.Auto2D or LaunchVariant.AutoLong2D
                or LaunchVariant.Auto2DStride
                or LaunchVariant.AutoLong2DStride => 2,
            LaunchVariant.Auto3D or LaunchVariant.AutoLong3D
                or LaunchVariant.Auto3DStride
                or LaunchVariant.AutoLong3DStride => 3,
            _ => 1
        };

        sb.AppendLine("        KernelConfig config,");
        sb.Append("        long userExtent");
        // Add dimension parameters for multi-dim launches
        for (int d = 0; d < indexDims && indexDims > 1; d++)
        {
            var dimName = d switch { 0 => "_dimX", 1 => "_dimY", _ => "_dimZ" };
            sb.Append($",\n        int {dimName}");
        }

        if (kernel.Parameters.Length == 0)
        {
            sb.AppendLine(")");
        }
        else
        {
            sb.AppendLine(",");
            for (int i = 0; i < kernel.Parameters.Length; i++)
            {
                var param = kernel.Parameters[i];
                var suffix = i < kernel.Parameters.Length - 1 ? "," : ")";
                sb.AppendLine(
                    $"        {FormatTypeName(param.Type)} {param.Name}{suffix}");
            }
        }
        if (whereClause.Length > 0)
            sb.Append(whereClause);
        sb.AppendLine("    {");
        sb.AppendLine("        // Stub — replaced by ILGPUC backend codegen");
        sb.AppendLine("        throw new NotSupportedException(\"No Kernel\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Formats a Roslyn type symbol as a C# type name string suitable for
    /// use in generated source code. Generic types are expanded recursively;
    /// well-known primitive types use their C# keyword aliases.
    /// </summary>
    /// <summary>
    /// Public entry point for formatting type names from external callers.
    /// </summary>
    public static string FormatTypeNamePublic(ITypeSymbol type) =>
        FormatTypeName(type);

    /// <summary>
    /// Extracts user-facing property/field accessor names for a struct type,
    /// in declaration order (matching the IR struct field order, which itself
    /// matches CLR metadata token order). Returns <see langword="null"/> for
    /// non-struct types or structs with no instance members.
    /// </summary>
    /// <remarks>
    /// Used by <see cref="MainKernelProvider"/> and the in-process test
    /// pipeline to thread user-side accessor names through to
    /// <c>CompiledKernelGenerator</c> so the generated launch wrapper can
    /// reference user struct fields by their original names instead of the
    /// synthetic <c>Field0</c>, <c>Field1</c>, ... fallback.
    /// </remarks>
    public static string[]? ExtractFieldAccessors(ITypeSymbol type)
    {
        if (type.TypeKind != TypeKind.Struct)
            return null;

        var accessors = new System.Collections.Generic.List<string>();
        FlattenFieldAccessors(type, "", accessors);

        return accessors.Count > 0 ? accessors.ToArray() : null;
    }

    /// <summary>
    /// Recursively extracts field accessor chains, flattening nested value
    /// types to match the IR's flat struct layout.
    /// For example, <c>ArrayView2D&lt;int, Stride2D.DenseX&gt;</c> has:
    /// <c>BaseView</c> (view), <c>Extent</c> (<c>LongIndex2D</c>),
    /// <c>Stride</c> (<c>Stride2D.DenseX</c>).
    /// The IR flattens this to: view, long (Extent.X), long (Extent.Y),
    /// int (Stride.YStride). This method produces accessor chains like
    /// <c>["BaseView", "Extent.X", "Extent.Y", "Stride.YStride"]</c>.
    /// </summary>
    private static void FlattenFieldAccessors(
        ITypeSymbol type,
        string prefix,
        System.Collections.Generic.List<string> result)
    {
        var fields = type.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => !f.IsStatic && !f.IsConst)
            .ToArray();

        foreach (var f in fields)
        {
            // Resolve the public-facing name
            string? name;
            if (f.AssociatedSymbol is IPropertySymbol prop)
                name = prop.Name;
            else
            {
                name = f.Name;
                if (name.StartsWith('<')
                    && name.EndsWith("k__BackingField", StringComparison.Ordinal))
                {
                    var endAngle = name.IndexOf('>', StringComparison.Ordinal);
                    if (endAngle > 1)
                        name = name[1..endAngle];
                }
                if (f.IsImplicitlyDeclared)
                    name = null;
            }

            if (name is null) continue;

            var fullName = prefix.Length > 0 ? $"{prefix}.{name}" : name;
            var fieldType = f.Type;

            // Check if this field should be recursively expanded.
            // Expand struct types that have instance fields and are NOT
            // view/pointer types (those are handled by the view path).
            if (fieldType.TypeKind == TypeKind.Struct
                && !IsViewOrPointerType(fieldType))
            {
                var subFields = fieldType.GetMembers()
                    .OfType<IFieldSymbol>()
                    .Where(sf => !sf.IsStatic && !sf.IsConst)
                    .ToArray();

                if (subFields.Length > 0
                    && fieldType.SpecialType == SpecialType.None)
                {
                    // Recursively flatten
                    FlattenFieldAccessors(fieldType, fullName, result);
                    continue;
                }
            }

            // Leaf field — add the accessor
            result.Add(fullName);
        }
    }

    /// <summary>
    /// Returns true if the type looks like a view or pointer-containing type
    /// that the IR treats as a single view field (not decomposed).
    /// </summary>
    private static bool IsViewOrPointerType(ITypeSymbol type)
    {
        var name = type.Name;
        // ArrayView, CPURuntimeView, ViewImplementation — all view wrappers
        if (name is "ArrayView" or "CPURuntimeView" or "ViewImplementation")
            return true;
        // Check for pointer/IntPtr fields which indicate view-like types
        return type.GetMembers()
            .OfType<IFieldSymbol>()
            .Any(f => !f.IsStatic && (
                f.Type.TypeKind == TypeKind.Pointer ||
                f.Type.TypeKind == TypeKind.FunctionPointer ||
                f.Type.Name is "IntPtr" or "UIntPtr" or "ViewHandle"));
    }

    private static string FormatTypeName(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.IsGenericType)
        {
            var baseName = named.Name;
            var typeArgs = string.Join(", ",
                named.TypeArguments.Select(FormatTypeName));
            return $"{baseName}<{typeArgs}>";
        }

        return type.SpecialType switch
        {
            SpecialType.System_Boolean => "bool",
            SpecialType.System_Byte => "byte",
            SpecialType.System_SByte => "sbyte",
            SpecialType.System_Int16 => "short",
            SpecialType.System_UInt16 => "ushort",
            SpecialType.System_Int32 => "int",
            SpecialType.System_UInt32 => "uint",
            SpecialType.System_Int64 => "long",
            SpecialType.System_UInt64 => "ulong",
            SpecialType.System_Single => "float",
            SpecialType.System_Double => "double",
            SpecialType.System_Char => "char",
            SpecialType.System_String => "string",
            _ => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                     .Replace("global::", "", StringComparison.Ordinal),
        };
    }

    /// <summary>
    /// Formats a type symbol using fully qualified names — including the
    /// namespace for generic types. Used for <c>where</c> constraint types
    /// which must be fully qualified in the generated stub source.
    /// </summary>
    private static string FormatTypeNameFull(ITypeSymbol type)
    {
        // For generic types like INumber<T>, use the full display string
        // so constraints resolve without extra using directives.
        if (type is INamedTypeSymbol named && named.IsGenericType)
        {
            // Get the fully-qualified open type name (e.g. System.Numerics.INumber)
            var baseName = named.OriginalDefinition
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", "", StringComparison.Ordinal);
            // Strip the generic arity suffix (e.g. INumber<T> display includes <T>)
            var angleIdx = baseName.IndexOf('<');
            if (angleIdx >= 0)
                baseName = baseName[..angleIdx];
            var typeArgs = string.Join(", ",
                named.TypeArguments.Select(FormatTypeName));
            return $"{baseName}<{typeArgs}>";
        }

        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                   .Replace("global::", "", StringComparison.Ordinal);
    }
}
