using ILGPU.Backends.EntryPoints;
using ILGPU.IR;
using ILGPU.IR.Analyses;
using ILGPU.IR.Values;
using ILGPU.Runtime;
using System;
using System.Text;

namespace ILGPU.Backends.SPIRV
{
    public class SPIRVBackend : CodeGeneratorBackend<
        SPIRVIntrinsic.Handler,
        SPIRVCodeGenerator.GeneratorArgs,
        SPIRVCodeGenerator,
        StringBuilder>
    {
        public SPIRVBackend(
            Context context,
            CapabilityContext capabilities,
            BackendType backendType,
            BackendFlags backendFlags,
            ArgumentMapper argumentMapper) :
            base(context,
                capabilities,
                backendType,
                backendFlags,
                argumentMapper)
        {
        }

        protected override StringBuilder CreateKernelBuilder(
            EntryPoint entryPoint,
            in BackendContext backendContext,
            in KernelSpecialization specialization,
            out SPIRVCodeGenerator.GeneratorArgs data)
        {
            backendContext.EnsureIntrinsicImplementations(IntrinsicProvider);

            var builder = new StringBuilder();
            const uint MagicNumber = 0x07230203;
            const uint Version = 0x00010200;
            const uint ILGPUGeneratorMagicNumber = 0x10101010;

            builder.AppendLine(";");
            builder.Append("; Generated by ILGPU v");
            builder.AppendLine(Context.Version);
            builder.AppendLine(";");

            builder.AppendLine($"; Magic: 0x{MagicNumber:X8} (SPIR-V)");
            builder.AppendLine(
                $"; Version: 0x{Version:X8} (Version: 1.2.0)");
            builder.AppendLine(
                $"; Generator: 0x{ILGPUGeneratorMagicNumber:X8} (ILGPU)");

            //TODO: Calculate bound or insert this after compilation
            builder.AppendLine("; Bound: ");
            builder.AppendLine("; Schema: 0");

            data = new SPIRVCodeGenerator.GeneratorArgs(
                this,
                entryPoint,
                new SPRIVTypeGenerator(),
                backendContext.SharedAllocations,
                backendContext.DynamicSharedAllocations);
            return builder;
        }

        protected override SPIRVCodeGenerator CreateFunctionCodeGenerator(
            Method method,
            Allocas allocas,
            SPIRVCodeGenerator.GeneratorArgs data) =>
            throw new NotImplementedException();

        protected override SPIRVCodeGenerator CreateKernelCodeGenerator(
            in AllocaKindInformation sharedAllocations,
            Method method,
            Allocas allocas,
            SPIRVCodeGenerator.GeneratorArgs data) => throw new NotImplementedException();

        protected override CompiledKernel CreateKernel(EntryPoint entryPoint,
            CompiledKernel.KernelInfo kernelInfo,
            StringBuilder builder, SPIRVCodeGenerator.GeneratorArgs data) =>
            throw new NotImplementedException();
    }
}
