// ---------------------------------------------------------------------------------------
//                                        ILGPU
//                           Copyright (c) 2026 ILGPU Project
//                                    www.ilgpu.net
//
// File: CodeGenerator.cs
//
// This file is part of ILGPU and is distributed under the University of Illinois Open
// Source License. See LICENSE.txt for details.
// ---------------------------------------------------------------------------------------


using ILGPU.Util;
using ILGPUC.Backends.CPU;
using ILGPUC.IR.ModuleValues;
using System.IO;
using System.Linq;
using System.Text;

namespace ILGPUC.Backends;

/// <summary>
/// Represents the result of a launcher code generation operation.
/// </summary>
/// <param name="LauncherSourceCode">The generated C# launcher source code.</param>
/// <param name="LauncherClassName">The name of the generated launcher class.</param>
readonly record struct LauncherGenerationResult(
    string LauncherSourceCode,
    string LauncherClassName);

/// <summary>
/// Represents the result of a code generation operation.
/// </summary>
/// <param name="SourceCode">The generated source code.</param>
/// <param name="EntryPointName">The name of the entry point function.</param>
/// <param name="Launcher">Optional launcher generation result.</param>
/// <param name="BufferPool">
/// Optional buffer pool metadata for CPU backend pooling.
/// </param>
/// <param name="KernelClassName">
/// The kernel class name that was used during generation.
/// </param>
/// <param name="EntryPointParamTypeNames">
/// The entry point kernel parameter type names that were used.
/// </param>
/// <param name="EntryPointIndexTypeName">
/// The post-backend-transform type name of the entry point's implicit
/// thread-index parameter, if any (e.g., <c>KernelIndex</c> for grouped
/// launches that expose a GridIndex/GroupIndex struct). <see langword="null"/>
/// when the entry point receives a scalar index or no index at all.
/// </param>
readonly record struct CodeGenerationResult(
    string SourceCode,
    string EntryPointName,
    LauncherGenerationResult? Launcher = null,
    BufferPoolMetadata? BufferPool = null,
    string? KernelClassName = null,
    string[]? EntryPointParamTypeNames = null,
    string? EntryPointIndexTypeName = null);

/// <summary>
/// Abstract base class for generating source code from ILGPU IR.
/// This class provides the core infrastructure for transforming a Module
/// into executable source code for C-like languages (Metal, OpenCL, CUDA, etc).
/// </summary>
/// <remarks>
/// Constructs a new code generator.
/// </remarks>
/// <param name="module">The module to generate code for.</param>
/// <param name="languageConfig">Language-specific configuration.</param>
sealed class CodeGenerator(Module module, LanguageConfiguration languageConfig)
{
    /// <summary>
    /// Generates source code for the entire module.
    /// This is the main entry point for code generation.
    /// </summary>
    /// <returns>The generated source code and entry point information.</returns>
    public CodeGenerationResult GenerateCode()
    {
        var builder = new StringBuilder(16 * 1024);
        using var writer = new StringWriter(builder);
        var context = new GenerationContext(module, languageConfig, writer);
        var typeEmitter = new TypeEmitter(context);

        // Generate code in the proper order
        GenerateHeader(context);
        GenerateTypeDeclarations(context);
        GenerateGlobalDeclarations(context);
        GenerateMethodDeclarations(context, typeEmitter);
        GenerateMethodImplementations(context, typeEmitter);

        return new CodeGenerationResult(
            writer.ToString(),
            GetEntryPointName(module.EntryPoint));
    }

    /// <summary>
    /// Generates the file header (includes, pragmas, etc).
    /// </summary>
    private void GenerateHeader(GenerationContext context)
    {
        // Emit header comment
        context.WriteLine("// ---------------------------------------------------");
        context.WriteLine("// Generated by ILGPU Compiler");
        context.WriteLine("// ---------------------------------------------------");
        context.WriteLine();

        // Emit includes/imports
        foreach (var include in languageConfig.GetHeaderIncludes())
            context.WriteLine(include);
        context.WriteLine();

        // Emit pragmas
        foreach (var pragma in languageConfig.GetPragmas())
            context.WriteLine(pragma);

        if (languageConfig.GetPragmas().Any())
            context.WriteLine();
    }

    /// <summary>
    /// Generates all type declarations (structures, etc).
    /// Types must be declared in dependency order.
    /// </summary>
    private static void GenerateTypeDeclarations(GenerationContext context)
    {
        var typeEmitter = new TypeEmitter(context);
        typeEmitter.EmitTypeDeclarations();
    }

    /// <summary>
    /// Generates file-scope global variable declarations.
    /// Globals whose address space is not file-scope-eligible
    /// (e.g. Metal thread/thread-group) are deferred to function scope.
    /// </summary>
    private void GenerateGlobalDeclarations(GenerationContext context)
    {
        var typeEmitter = new TypeEmitter(context);
        bool any = false;

        foreach (var global in module.Globals)
        {
            if (!languageConfig.IsFileScopeAddressSpace(global.AddressSpace))
                continue;
            EmitGlobalDeclaration(context, typeEmitter, global);
            any = true;
        }

        if (any)
            context.WriteLine();
    }

    /// <summary>
    /// Emits a single global variable declaration.
    /// </summary>
    internal static void EmitGlobalDeclaration(
        GenerationContext context,
        TypeEmitter typeEmitter,
        Global global)
    {
        var addressSpace = global.AddressSpace;
        var addressSpaceKeyword = context.LanguageConfig.GetAddressSpaceKeyword(
            addressSpace);
        var typeName = typeEmitter.GetTypeName(global.AllocType);
        var globalName = context.GetValueName(global);

        // Emit with address space qualifier
        if (!string.IsNullOrEmpty(addressSpaceKeyword))
            context.Write($"{addressSpaceKeyword} ");

        context.Write($"{typeName} {globalName}");

        // Handle array allocations
        if (global.ArrayLength.HasValue)
        {
            var arraySize = global.ArrayLength.Value.Int32Value;
            context.Write($"[{arraySize}]");
        }

        context.WriteLine(";");
    }

    /// <summary>
    /// Generates method forward declarations.
    /// </summary>
    private static void GenerateMethodDeclarations(
        GenerationContext context,
        TypeEmitter typeEmitter)
    {
        var expressionEmitter = new ExpressionEmitter(context, typeEmitter);
        var methodEmitter = new MethodEmitter(context, typeEmitter, expressionEmitter);

        methodEmitter.EmitMethodDeclarations();
    }

    /// <summary>
    /// Generates method implementations.
    /// </summary>
    private static void GenerateMethodImplementations(
        GenerationContext context,
        TypeEmitter typeEmitter)
    {
        var expressionEmitter = new ExpressionEmitter(context, typeEmitter);
        var methodEmitter = new MethodEmitter(context, typeEmitter, expressionEmitter);

        methodEmitter.EmitMethodImplementations();
    }

    /// <summary>
    /// Gets the name to use for the entry point function.
    /// </summary>
    private static string GetEntryPointName(Method entryPoint) =>
        GenerationContext.GetMethodName(entryPoint);
}
