// ---------------------------------------------------------------------------------------
//                                        ILGPU
//                           Copyright (c) 2026 ILGPU Project
//                                    www.ilgpu.net
//
// File: CompiledKernelSourceGenerator.cs
//
// This file is part of ILGPU and is distributed under the University of Illinois Open
// Source License. See LICENSE.txt for details.
// ---------------------------------------------------------------------------------------


// disable: max_line_length
using ILGPU.Runtime;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace ILGPUC.Backends;

/// <summary>
/// Generates a per-backend static registrar class with a <c>[ModuleInitializer]</c>
/// that registers all compiled kernels of a given backend with the ILGPU context.
/// </summary>
static class KernelRegistrarGenerator
{
    /// <summary>
    /// Generates a kernel registrar class for a specific backend type.
    /// </summary>
    /// <param name="acceleratorType">The backend's accelerator type.</param>
    /// <param name="kernelClassNames">All compiled kernel class names for this backend.</param>
    /// <returns>The generated C# source code.</returns>
    public static string Generate(
        AcceleratorType acceleratorType,
        IReadOnlyList<string> kernelClassNames)
    {
        var builder = new StringBuilder(2 * 1024);
        using var writer = new StringWriter(builder);

        writer.WriteLine("// ---------------------------------------------------------");
        writer.WriteLine("// Generated by ILGPU Compiler — Kernel Registrar");
        writer.WriteLine("// ---------------------------------------------------------");
        writer.WriteLine();
        writer.WriteLine("using System.Runtime.CompilerServices;");
        writer.WriteLine("using ILGPU;");
        writer.WriteLine("using ILGPU.Runtime;");
        writer.WriteLine();

        var className = $"{acceleratorType}KernelRegistrar";
        writer.WriteLine($"internal static class {className}");
        writer.WriteLine("{");
        writer.WriteLine("    [ModuleInitializer]");
        writer.WriteLine("    internal static void Register()");
        writer.WriteLine("    {");

        foreach (var kernelClassName in kernelClassNames)
        {
            writer.WriteLine(
                $"        Context.RegisterKernels<{kernelClassName}>" +
                $"([new {kernelClassName}()]);");
        }

        writer.WriteLine("    }");
        writer.WriteLine("}");

        return writer.ToString();
    }
}
