source "https://rubygems.org"

### dev + gh-pages emulation dependencies ###
group :jekyll_plugins do
  gem 'github-pages'  # emulates github-pages environment
  gem "bundler"  # Gems manager (optional)
  gem "rake"  # build utility (optional)
  gem "webrick", '~> 1.7'  # HTTP server toolkit, fix for ruby >= 3.0
end
### dev + gh-pages emulation dependencies ###

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
