// ---------------------------------------------------------------------------------------
//                                        ILGPU
//                           Copyright (c) 2026 ILGPU Project
//                                    www.ilgpu.net
//
// File: CompiledKernel.cs
//
// This file is part of ILGPU and is distributed under the University of Illinois Open
// Source License. See LICENSE.txt for details.
// ---------------------------------------------------------------------------------------

using System;

namespace ILGPU.Runtime;

/// <summary>
/// The type of a compiled kernel to differentiate between grouped and automatic kernels.
/// </summary>
public enum CompiledKernelType
{
    /// <summary>
    /// An automatic kernel that relies on runtime group information.
    /// </summary>
    Auto,

    /// <summary>
    /// An explicitly grouped kernel that provides fixed grouping information.
    /// </summary>
    Grouped,
}

/// <summary>
/// Specifies modes to provide shared memory at runtime.
/// </summary>
public enum CompiledKernelSharedMemoryMode
{
    /// <summary>
    /// Static shared memory provided by the compiler.
    /// </summary>
    Static,

    /// <summary>
    /// Dynamic shared memory provided by the runtime.
    /// </summary>
    Dynamic,

    /// <summary>
    /// Dynamic shared memory provided by the runtime and also static shared memory
    /// required to be provided by the compiler. This can be treated as dynamic by
    /// the runtime.
    /// </summary>
    Hybrid,
}

/// <summary>
/// Adjusts kernel configurations to adjust specific settings like shared memory.
/// </summary>
/// <param name="kernelConfig">The kernel configuration to adjust.</param>
public delegate void CompiledKernelConfigAdjustment(ref KernelConfig kernelConfig);

/// <summary>
/// Represents a statically known compiled kernel kind.
/// </summary>
public interface ICompiledKernelKind
{
    /// <summary>
    /// Returns the general accelerator type.
    /// </summary>
    static abstract AcceleratorType GeneralAcceleratorType { get; }
}

/// <summary>
/// Represents a compiled kernel object generated by ILGPUC.
/// </summary>
public abstract class CompiledKernel(
    Guid guid,
    string kernelName,
    CompiledKernelType kernelType,
    CompiledKernelSharedMemoryMode sharedMemoryMode)
{
    /// <summary>
    /// Returns the entry point function name in the compiled kernel source.
    /// </summary>
    public string KernelName { get; } = kernelName;

    /// <summary>
    /// Returns the unique kernel id.
    /// </summary>
    public Guid Guid { get; } = guid;

    /// <summary>
    /// Returns the kernel type.
    /// </summary>
    public CompiledKernelType KernelType { get; } = kernelType;

    /// <summary>
    /// Returns the shared memory mode.
    /// </summary>
    public CompiledKernelSharedMemoryMode SharedMemoryMode { get; } = sharedMemoryMode;

    /// <summary>
    /// Returns the underlying accelerator type required to load and launch this kernel.
    /// </summary>
    public AcceleratorType AcceleratorType => RequiredCapabilities.AcceleratorType;

    /// <summary>
    /// Returns the minimum accelerator capabilities this kernel requires to execute.
    /// </summary>
    public abstract AcceleratorCapabilities RequiredCapabilities { get; }

    /// <summary>
    /// Called by the accelerator after loading this compiled kernel into a
    /// runtime <see cref="Kernel"/>. Subclasses can override to cache the
    /// loaded kernel for zero-cost access at launch time.
    /// </summary>
    /// <param name="kernel">The loaded runtime kernel.</param>
    protected internal virtual void OnKernelLoaded(Kernel kernel) { }

    /// <summary>
    /// Returns the underlying kernel source as string.
    /// </summary>
    /// <returns>The string representation of the kernel source.</returns>
    public abstract string GetSourceAsString();

    /// <summary>
    /// Returns the pre-compiled kernel binary data.
    /// </summary>
    /// <returns>The compiled binary data.</returns>
    public virtual ReadOnlyMemory<byte> GetCompiledBinary() =>
        throw new NotSupportedException(
            "This compiled kernel does not contain pre-compiled binary data.");

    /// <summary>
    /// Returns the pre-compiled kernel binary data, or an empty memory if
    /// no binary is available.
    /// </summary>
    /// <returns>The compiled binary data or empty.</returns>
    public virtual ReadOnlyMemory<byte> GetCompiledBinaryOrDefault() =>
        ReadOnlyMemory<byte>.Empty;
}
