<Project>
  <PropertyGroup Condition="'$(MSBuildVersion)' &gt;= '17.8'">
    <LibrarySamplesTargetFrameworks>net8.0</LibrarySamplesTargetFrameworks>
    <LibrarySamplesTargetFrameworksWindows>net8.0-windows</LibrarySamplesTargetFrameworksWindows>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildVersion)' &lt; '17.8'">
    <LibrarySamplesTargetFrameworks>net471</LibrarySamplesTargetFrameworks>
    <LibrarySamplesTargetFrameworksWindows>net471</LibrarySamplesTargetFrameworksWindows>
  </PropertyGroup>
  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <LibrarySamplesTargetFrameworks>net471;net8.0</LibrarySamplesTargetFrameworks>
    <LibrarySamplesTargetFrameworksWindows>net471;net8.0-windows</LibrarySamplesTargetFrameworksWindows>
  </PropertyGroup>

</Project>
