//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILGPU.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ILGPU.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the field &apos;{0}&apos; of type &apos;{1}&apos;.
        /// </summary>
        internal static string CannotFindFieldOfType {
            get {
                return ResourceManager.GetString("CannotFindFieldOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load required LLVM library.
        /// </summary>
        internal static string CannotLoadLLVMLib {
            get {
                return ResourceManager.GetString("CannotLoadLLVMLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot take field offset of primitive type &apos;{0}&apos;.
        /// </summary>
        internal static string CannotTakeFieldOffsetOfPrimitiveType {
            get {
                return ResourceManager.GetString("CannotTakeFieldOffsetOfPrimitiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not generate machine code: &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotGenerateMachineCode {
            get {
                return ResourceManager.GetString("CouldNotGenerateMachineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load lib-device library: &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotLoadLibDevice {
            get {
                return ResourceManager.GetString("CouldNotLoadLibDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read lib-device library: &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotReadLibDevice {
            get {
                return ResourceManager.GetString("CouldNotReadLibDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuda path could not be determined automatically. Custom device library could not be found..
        /// </summary>
        internal static string CudaPathNotFound {
            get {
                return ResourceManager.GetString("CudaPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; requires a custom ABI implementation.
        /// </summary>
        internal static string CustomABIImplementationRequired {
            get {
                return ResourceManager.GetString("CustomABIImplementationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; has custom exception semantics..
        /// </summary>
        internal static string CustomExceptionSemantics {
            get {
                return ResourceManager.GetString("CustomExceptionSemantics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}.{1}&apos; requires an explicit memory offset.
        /// </summary>
        internal static string ExplicitMemoryOffsetRequired {
            get {
                return ResourceManager.GetString("ExplicitMemoryOffsetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entry point must receive at least one index parameter.
        /// </summary>
        internal static string InvalidEntryPointIndexParameter {
            get {
                return ResourceManager.GetString("InvalidEntryPointIndexParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entry point must receive a compatible index type as first parameter.
        /// </summary>
        internal static string InvalidEntryPointIndexParameterOfWrongType {
            get {
                return ResourceManager.GetString("InvalidEntryPointIndexParameterOfWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only static methods are supported at the moment.
        /// </summary>
        internal static string InvalidEntryPointInstanceKernelMethod {
            get {
                return ResourceManager.GetString("InvalidEntryPointInstanceKernelMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IL Code.
        /// </summary>
        internal static string InvalidILCode {
            get {
                return ResourceManager.GetString("InvalidILCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid math-intrinsic implementation of &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidMathIntrinsic {
            get {
                return ResourceManager.GetString("InvalidMathIntrinsic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable views cannot have a specified element count in shared memory. Consider using an array view instead..
        /// </summary>
        internal static string InvalidUseOfVariableViewsInSharedMemory {
            get {
                return ResourceManager.GetString("InvalidUseOfVariableViewsInSharedMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a compatible lib-device library.
        /// </summary>
        internal static string LibDeviceNotFound {
            get {
                return ResourceManager.GetString("LibDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom device-library path could not be determined automatically. Try specifying the path explicitly..
        /// </summary>
        internal static string LibDevicePathNotFound {
            get {
                return ResourceManager.GetString("LibDevicePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLVM-module verification failed: {0}.
        /// </summary>
        internal static string LLVMModuleVerificationFailed {
            get {
                return ResourceManager.GetString("LLVMModuleVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided types &apos;{0}&apos; and &apos;{1}&apos; do not match.
        /// </summary>
        internal static string MismatchingTypes {
            get {
                return ResourceManager.GetString("MismatchingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native method &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string NativeMethodNotSupported {
            get {
                return ResourceManager.GetString("NativeMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is only permitted in native-OS-platform mode. The current runtime is &apos;{0}&apos; but the native OS platform is &apos;{1}&apos;.
        /// </summary>
        internal static string NativePlatformInvocationRequired {
            get {
                return ResourceManager.GetString("NativePlatformInvocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation &apos;{0}&apos; on the .Net activator is not supported..
        /// </summary>
        internal static string NotSupportedActivatorOperation {
            get {
                return ResourceManager.GetString("NotSupportedActivatorOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported arithmetic operands &apos;{0}&apos; &amp; &apos;{1}&apos;.
        /// </summary>
        internal static string NotSupportedArithmeticOperandTypes {
            get {
                return ResourceManager.GetString("NotSupportedArithmeticOperandTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a dynamically sized array on an accelerator.
        /// </summary>
        internal static string NotSupportedArrayCreation {
            get {
                return ResourceManager.GetString("NotSupportedArrayCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array type &apos;{0}&apos; uses a non-value element type.
        /// </summary>
        internal static string NotSupportedArrayElementType {
            get {
                return ResourceManager.GetString("NotSupportedArrayElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic operation of type &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string NotSupportedAtomicOperation {
            get {
                return ResourceManager.GetString("NotSupportedAtomicOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported backend.
        /// </summary>
        internal static string NotSupportedBackend {
            get {
                return ResourceManager.GetString("NotSupportedBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxing a value is currently not supported.
        /// </summary>
        internal static string NotSupportedBoxing {
            get {
                return ResourceManager.GetString("NotSupportedBoxing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class type &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string NotSupportedClassType {
            get {
                return ResourceManager.GetString("NotSupportedClassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported compare operation of types &apos;{0}&apos; &amp; &apos;{1}&apos;.
        /// </summary>
        internal static string NotSupportedCompareOperation {
            get {
                return ResourceManager.GetString("NotSupportedCompareOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported compare or arithmetic value of type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedCompareOrArithmeticValue {
            get {
                return ResourceManager.GetString("NotSupportedCompareOrArithmeticValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported compile unit.
        /// </summary>
        internal static string NotSupportedCompileUnit {
            get {
                return ResourceManager.GetString("NotSupportedCompileUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported conversion.
        /// </summary>
        internal static string NotSupportedConversion {
            get {
                return ResourceManager.GetString("NotSupportedConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported float comparison of type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedFloatComparison {
            get {
                return ResourceManager.GetString("NotSupportedFloatComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported float conversion.
        /// </summary>
        internal static string NotSupportedFloatConversion {
            get {
                return ResourceManager.GetString("NotSupportedFloatConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported generic method &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedGenericMethod {
            get {
                return ResourceManager.GetString("NotSupportedGenericMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic type &apos;{0}&apos; without required type arguments cannot be converted to an object type.
        /// </summary>
        internal static string NotSupportedGenericType {
            get {
                return ResourceManager.GetString("NotSupportedGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported grid intrinsic of type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedGridIntrinsic {
            get {
                return ResourceManager.GetString("NotSupportedGridIntrinsic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported group intrinsic of type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedGroupIntrinsic {
            get {
                return ResourceManager.GetString("NotSupportedGroupIntrinsic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported IL instruction in method of type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedILInstruction {
            get {
                return ResourceManager.GetString("NotSupportedILInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported IL instruction in method of type &apos;{0}&apos;. Are you using a lambda closure?.
        /// </summary>
        internal static string NotSupportedILInstructionPossibleLambda {
            get {
                return ResourceManager.GetString("NotSupportedILInstructionPossibleLambda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported indirect call to a method with the signature &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedIndirectMethodCall {
            get {
                return ResourceManager.GetString("NotSupportedIndirectMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported instruction in method &apos;{0}&apos; of type &apos;{1}&apos;..
        /// </summary>
        internal static string NotSupportedInstruction {
            get {
                return ResourceManager.GetString("NotSupportedInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported int comparison of type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedIntComparison {
            get {
                return ResourceManager.GetString("NotSupportedIntComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported int conversion.
        /// </summary>
        internal static string NotSupportedIntConversion {
            get {
                return ResourceManager.GetString("NotSupportedIntConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface type &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string NotSupportedInterfaceType {
            get {
                return ResourceManager.GetString("NotSupportedInterfaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported int operand of type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedIntOperand {
            get {
                return ResourceManager.GetString("NotSupportedIntOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported intrinsic type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedIntrinsic {
            get {
                return ResourceManager.GetString("NotSupportedIntrinsic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInstance is currently not supported.
        /// </summary>
        internal static string NotSupportedIsInstance {
            get {
                return ResourceManager.GetString("NotSupportedIsInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported kernel-parameter type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedKernelParameterType {
            get {
                return ResourceManager.GetString("NotSupportedKernelParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load from the static field &apos;{0}&apos; since it is not read only.
        /// </summary>
        internal static string NotSupportedLoadOfStaticField {
            get {
                return ResourceManager.GetString("NotSupportedLoadOfStaticField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot take address of the static field &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedLoadOfStaticFieldAddress {
            get {
                return ResourceManager.GetString("NotSupportedLoadOfStaticFieldAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported math intrinsic of type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedMathIntrinsic {
            get {
                return ResourceManager.GetString("NotSupportedMathIntrinsic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported memory-fence operation of type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedMemoryFenceOperation {
            get {
                return ResourceManager.GetString("NotSupportedMemoryFenceOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported jump to method &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedMethodJump {
            get {
                return ResourceManager.GetString("NotSupportedMethodJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported platform &apos;{0}&apos; ({1} required).
        /// </summary>
        internal static string NotSupportedPlatform {
            get {
                return ResourceManager.GetString("NotSupportedPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported pointer conversion.
        /// </summary>
        internal static string NotSupportedPointerConversion {
            get {
                return ResourceManager.GetString("NotSupportedPointerConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointer type &apos;{0}&apos; cannot be converted to an object type.
        /// </summary>
        internal static string NotSupportedPointerToObjectType {
            get {
                return ResourceManager.GetString("NotSupportedPointerToObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primitive type &apos;{0}&apos; cannot be converted to an object type.
        /// </summary>
        internal static string NotSupportedPrimitiveToObjectType {
            get {
                return ResourceManager.GetString("NotSupportedPrimitiveToObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported recursive program.
        /// </summary>
        internal static string NotSupportedRecursiveProgram {
            get {
                return ResourceManager.GetString("NotSupportedRecursiveProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported runtime method &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedRuntimeMethod {
            get {
                return ResourceManager.GetString("NotSupportedRuntimeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported shared-memory variable of type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedSharedMemoryVariableType {
            get {
                return ResourceManager.GetString("NotSupportedSharedMemoryVariableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot store a value to the static field &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedStoreToStaticField {
            get {
                return ResourceManager.GetString("NotSupportedStoreToStaticField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String operations are not supported.
        /// </summary>
        internal static string NotSupportedStringOperation {
            get {
                return ResourceManager.GetString("NotSupportedStringOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The struct type &apos;{0}&apos; requires an explicit packing.
        /// </summary>
        internal static string NotSupportedStructDueToExplicitPacking {
            get {
                return ResourceManager.GetString("NotSupportedStructDueToExplicitPacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The struct type &apos;{0}&apos; requires an explicit size.
        /// </summary>
        internal static string NotSupportedStructDueToExplicitSize {
            get {
                return ResourceManager.GetString("NotSupportedStructDueToExplicitSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The struct type &apos;{0}&apos; requires a non-ansi charset.
        /// </summary>
        internal static string NotSupportedStructDueToNonAnsiCharSet {
            get {
                return ResourceManager.GetString("NotSupportedStructDueToNonAnsiCharSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The struct type &apos;{0}&apos; requires a non-sequential memory layout.
        /// </summary>
        internal static string NotSupportedStructDueToNonSequentialMemoryLayout {
            get {
                return ResourceManager.GetString("NotSupportedStructDueToNonSequentialMemoryLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported target platform.
        /// </summary>
        internal static string NotSupportedTargetPlatform {
            get {
                return ResourceManager.GetString("NotSupportedTargetPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedType {
            get {
                return ResourceManager.GetString("NotSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unboxing a value is currently not supported.
        /// </summary>
        internal static string NotSupportedUnboxing {
            get {
                return ResourceManager.GetString("NotSupportedUnboxing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported unsafe allocation on stack.
        /// </summary>
        internal static string NotSupportedUnsafeAllocation {
            get {
                return ResourceManager.GetString("NotSupportedUnsafeAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported unsigned to float conversion.
        /// </summary>
        internal static string NotSupportedUnsignedToFloatConversion {
            get {
                return ResourceManager.GetString("NotSupportedUnsignedToFloatConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared memory can only be used in the context of a grouped kernel. Consider using a grouped index..
        /// </summary>
        internal static string NotSupportedUseOfSharedMemory {
            get {
                return ResourceManager.GetString("NotSupportedUseOfSharedMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported value &apos;{0}&apos; of type &apos;{1}&apos;.
        /// </summary>
        internal static string NotSupportedValue {
            get {
                return ResourceManager.GetString("NotSupportedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported virtual call to method &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedVirtualMethodCall {
            get {
                return ResourceManager.GetString("NotSupportedVirtualMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported virtual call to method &apos;{0}&apos; defined in type &apos;{1}&apos; that was called on &apos;{2}&apos;.
        /// </summary>
        internal static string NotSupportedVirtualMethodCallToObject {
            get {
                return ResourceManager.GetString("NotSupportedVirtualMethodCallToObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling the virtual method &apos;{0}&apos; of unconstrained instance is not supported.
        /// </summary>
        internal static string NotSupportedVirtualMethodCallToUnconstrainedInstance {
            get {
                return ResourceManager.GetString("NotSupportedVirtualMethodCallToUnconstrainedInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported warp intrinsic of type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedWarpIntrinsic {
            get {
                return ResourceManager.GetString("NotSupportedWarpIntrinsic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The warp-shuffle function &apos;{0}&apos; is not supported in the scope of implicitly grouped kernels.
        /// </summary>
        internal static string NotSupportedWarpShuffle {
            get {
                return ResourceManager.GetString("NotSupportedWarpShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime-internal method &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string RuntimeInternalMethodNotSupported {
            get {
                return ResourceManager.GetString("RuntimeInternalMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not represent an array type.
        /// </summary>
        internal static string WrongArrayType {
            get {
                return ResourceManager.GetString("WrongArrayType", resourceCulture);
            }
        }
    }
}
