//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILGPU.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ILGPU.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly version &apos;{0}&apos; is not compatible with the current version &apos;{1}&apos;.
        /// </summary>
        internal static string AssemblyVersionNotCompatible {
            get {
                return ResourceManager.GetString("AssemblyVersionNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate node id &apos;{0}&apos; detected.
        /// </summary>
        internal static string CannotDeserializeDuplicateNodeId {
            get {
                return ResourceManager.GetString("CannotDeserializeDuplicateNodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the field &apos;{0}&apos; of type &apos;{1}&apos;.
        /// </summary>
        internal static string CannotFindFieldOfType {
            get {
                return ResourceManager.GetString("CannotFindFieldOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context flags &apos;{0}&apos; of the deserialized context are not compatible with the current flags &apos;{1}&apos;.
        /// </summary>
        internal static string ContextFlagsAreNotCompatible {
            get {
                return ResourceManager.GetString("ContextFlagsAreNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load method &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotDeserializeMethod {
            get {
                return ResourceManager.GetString("CouldNotDeserializeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load type &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotDeserializeType {
            get {
                return ResourceManager.GetString("CouldNotDeserializeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find IR method that corresponds to the method handle &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotFindCorrespondingIRMethod {
            get {
                return ResourceManager.GetString("CouldNotFindCorrespondingIRMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; has custom exception semantics..
        /// </summary>
        internal static string CustomExceptionSemantics {
            get {
                return ResourceManager.GetString("CustomExceptionSemantics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrinsic accelerators broken (contact developers).
        /// </summary>
        internal static string IntrinsicAcceleratorsBroken {
            get {
                return ResourceManager.GetString("IntrinsicAcceleratorsBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entry point must receive at least one index parameter.
        /// </summary>
        internal static string InvalidEntryPointIndexParameter {
            get {
                return ResourceManager.GetString("InvalidEntryPointIndexParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entry point must receive a compatible index type as first parameter.
        /// </summary>
        internal static string InvalidEntryPointIndexParameterOfWrongType {
            get {
                return ResourceManager.GetString("InvalidEntryPointIndexParameterOfWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only static methods are supported at the moment.
        /// </summary>
        internal static string InvalidEntryPointInstanceKernelMethod {
            get {
                return ResourceManager.GetString("InvalidEntryPointInstanceKernelMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported by-ref kernel parameter.
        /// </summary>
        internal static string InvalidEntryPointParameter {
            get {
                return ResourceManager.GetString("InvalidEntryPointParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported entry point without a valid .Net runtime entry.
        /// </summary>
        internal static string InvalidEntryPointWithoutDotNetMethod {
            get {
                return ResourceManager.GetString("InvalidEntryPointWithoutDotNetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IL Code.
        /// </summary>
        internal static string InvalidILCode {
            get {
                return ResourceManager.GetString("InvalidILCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can only be called from an ILGPU kernel.
        /// </summary>
        internal static string InvalidKernelOperation {
            get {
                return ResourceManager.GetString("InvalidKernelOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native method &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string NativeMethodNotSupported {
            get {
                return ResourceManager.GetString("NativeMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is only permitted in native-OS-platform mode. The current runtime is &apos;{0}&apos; but the native OS platform is &apos;{1}&apos;.
        /// </summary>
        internal static string NativePlatformInvocationRequired {
            get {
                return ResourceManager.GetString("NativePlatformInvocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation &apos;{0}&apos; on the .Net activator is not supported..
        /// </summary>
        internal static string NotSupportedActivatorOperation {
            get {
                return ResourceManager.GetString("NotSupportedActivatorOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not supported in the scope of this arithmetic operation.
        /// </summary>
        internal static string NotSupportedArithmeticArgumentType {
            get {
                return ResourceManager.GetString("NotSupportedArithmeticArgumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported arithmetic operands &apos;{0}&apos; &amp; &apos;{1}&apos;.
        /// </summary>
        internal static string NotSupportedArithmeticOperandTypes {
            get {
                return ResourceManager.GetString("NotSupportedArithmeticOperandTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a dynamically sized array on an accelerator.
        /// </summary>
        internal static string NotSupportedArrayCreation {
            get {
                return ResourceManager.GetString("NotSupportedArrayCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array type &apos;{0}&apos; uses a non-value element type.
        /// </summary>
        internal static string NotSupportedArrayElementType {
            get {
                return ResourceManager.GetString("NotSupportedArrayElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported by-ref kernel parameters.
        /// </summary>
        internal static string NotSupportedByRefKernelParameters {
            get {
                return ResourceManager.GetString("NotSupportedByRefKernelParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class type &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string NotSupportedClassType {
            get {
                return ResourceManager.GetString("NotSupportedClassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not supported in the scope of this compare operation.
        /// </summary>
        internal static string NotSupportedCompareArgumentType {
            get {
                return ResourceManager.GetString("NotSupportedCompareArgumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported compare or arithmetic value of type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedCompareOrArithmeticValue {
            get {
                return ResourceManager.GetString("NotSupportedCompareOrArithmeticValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert from &apos;{0}&apos; to type &apos;{1}&apos;.
        /// </summary>
        internal static string NotSupportedConversion {
            get {
                return ResourceManager.GetString("NotSupportedConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast type &apos;{0}&apos; to float/int.
        /// </summary>
        internal static string NotSupportedFloatIntCast {
            get {
                return ResourceManager.GetString("NotSupportedFloatIntCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported IL instruction in method &apos;{0}&apos; of type &apos;{1}&apos;.
        /// </summary>
        internal static string NotSupportedILInstruction {
            get {
                return ResourceManager.GetString("NotSupportedILInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported IL instruction in method &apos;{0}&apos; of type &apos;{1}&apos; (see {2}).
        /// </summary>
        internal static string NotSupportedILInstructionDebugLoc {
            get {
                return ResourceManager.GetString("NotSupportedILInstructionDebugLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported IL instruction in method &apos;{0}&apos; of type &apos;{1}&apos;. Are you using a lambda closure? (see {2}).
        /// </summary>
        internal static string NotSupportedILInstructionPossibleLambda {
            get {
                return ResourceManager.GetString("NotSupportedILInstructionPossibleLambda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported indirect call to a method with the signature &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedIndirectMethodCall {
            get {
                return ResourceManager.GetString("NotSupportedIndirectMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported instruction in method &apos;{0}&apos; of type &apos;{1}&apos;..
        /// </summary>
        internal static string NotSupportedInstruction {
            get {
                return ResourceManager.GetString("NotSupportedInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface type &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string NotSupportedInterfaceType {
            get {
                return ResourceManager.GetString("NotSupportedInterfaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interop intrinsic &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string NotSupportedInteropIntrinsic {
            get {
                return ResourceManager.GetString("NotSupportedInteropIntrinsic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported int operand of type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedIntOperand {
            get {
                return ResourceManager.GetString("NotSupportedIntOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported intrinsic type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedIntrinsic {
            get {
                return ResourceManager.GetString("NotSupportedIntrinsic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInstance is currently not supported.
        /// </summary>
        internal static string NotSupportedIsInstance {
            get {
                return ResourceManager.GetString("NotSupportedIsInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported kernel-parameter type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedKernelParameterType {
            get {
                return ResourceManager.GetString("NotSupportedKernelParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load from the static field &apos;{0}&apos; since it is not read only.
        /// </summary>
        internal static string NotSupportedLoadOfStaticField {
            get {
                return ResourceManager.GetString("NotSupportedLoadOfStaticField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The math intrinsic with {0} arguments is not supported.
        /// </summary>
        internal static string NotSupportedMathIntrinsic {
            get {
                return ResourceManager.GetString("NotSupportedMathIntrinsic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported jump to method &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedMethodJump {
            get {
                return ResourceManager.GetString("NotSupportedMethodJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported platform &apos;{0}&apos; ({1} required).
        /// </summary>
        internal static string NotSupportedPlatform {
            get {
                return ResourceManager.GetString("NotSupportedPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported recursive program.
        /// </summary>
        internal static string NotSupportedRecursiveProgram {
            get {
                return ResourceManager.GetString("NotSupportedRecursiveProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported runtime method &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedRuntimeMethod {
            get {
                return ResourceManager.GetString("NotSupportedRuntimeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shared memory intrinsic &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string NotSupportedSharedMemoryIntrinsic {
            get {
                return ResourceManager.GetString("NotSupportedSharedMemoryIntrinsic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve the native size of the type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedSizeOf {
            get {
                return ResourceManager.GetString("NotSupportedSizeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot store a value to the static field &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedStoreToStaticField {
            get {
                return ResourceManager.GetString("NotSupportedStoreToStaticField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported type &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedType {
            get {
                return ResourceManager.GetString("NotSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view intrinsic &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string NotSupportedViewIntrinsic {
            get {
                return ResourceManager.GetString("NotSupportedViewIntrinsic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported virtual call to method &apos;{0}&apos;.
        /// </summary>
        internal static string NotSupportedVirtualMethodCall {
            get {
                return ResourceManager.GetString("NotSupportedVirtualMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported virtual call to method &apos;{0}&apos; defined in type &apos;{1}&apos; that was called on &apos;{2}&apos;.
        /// </summary>
        internal static string NotSupportedVirtualMethodCallToObject {
            get {
                return ResourceManager.GetString("NotSupportedVirtualMethodCallToObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling the virtual method &apos;{0}&apos; of unconstrained instance is not supported.
        /// </summary>
        internal static string NotSupportedVirtualMethodCallToUnconstrainedInstance {
            get {
                return ResourceManager.GetString("NotSupportedVirtualMethodCallToUnconstrainedInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The warp intrinsic &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string NotSupportedWarpIntrinsic {
            get {
                return ResourceManager.GetString("NotSupportedWarpIntrinsic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no uses to resolve.
        /// </summary>
        internal static string NoUses {
            get {
                return ResourceManager.GetString("NoUses", resourceCulture);
            }
        }
    }
}
