//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILGPU.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuntimeErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuntimeErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ILGPU.Resources.RuntimeErrorMessages", typeof(RuntimeErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enable peer access to an accelerator of a different kind.
        /// </summary>
        internal static string CannotEnablePeerAccessToDifferentAcceleratorKind {
            get {
                return ResourceManager.GetString("CannotEnablePeerAccessToDifferentAcceleratorKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error-description string could not be resolved.
        /// </summary>
        internal static string CannotResolveErrorString {
            get {
                return ResourceManager.GetString("CannotResolveErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuda is not supported on this platform.
        /// </summary>
        internal static string CudaNotSupported {
            get {
                return ResourceManager.GetString("CudaNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid custom group size &gt; 0 in a grouped-index scenario.
        /// </summary>
        internal static string InvalidCustomGroupSize {
            get {
                return ResourceManager.GetString("InvalidCustomGroupSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid grid dimension.
        /// </summary>
        internal static string InvalidGridDimension {
            get {
                return ResourceManager.GetString("InvalidGridDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid group dimension.
        /// </summary>
        internal static string InvalidGroupDimension {
            get {
                return ResourceManager.GetString("InvalidGroupDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given kernel specialization is not compatible with the defined group size..
        /// </summary>
        internal static string InvalidKernelSpecializationGroupSize {
            get {
                return ResourceManager.GetString("InvalidKernelSpecializationGroupSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of provided arguments does not match the required length.
        /// </summary>
        internal static string InvalidNumberOfUniformArgs {
            get {
                return ResourceManager.GetString("InvalidNumberOfUniformArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared-memory size cannot be &lt; 0.
        /// </summary>
        internal static string InvalidSharedMemorySize {
            get {
                return ResourceManager.GetString("InvalidSharedMemorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported explicitly-grouped kernel.
        /// </summary>
        internal static string NotSupportedExplicitlyGroupedKernel {
            get {
                return ResourceManager.GetString("NotSupportedExplicitlyGroupedKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported index type.
        /// </summary>
        internal static string NotSupportedIndexType {
            get {
                return ResourceManager.GetString("NotSupportedIndexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported kernel.
        /// </summary>
        internal static string NotSupportedKernel {
            get {
                return ResourceManager.GetString("NotSupportedKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given kernel specialization is not compatible with the current accelerator..
        /// </summary>
        internal static string NotSupportedKernelSpecialization {
            get {
                return ResourceManager.GetString("NotSupportedKernelSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported OS platform.
        /// </summary>
        internal static string NotSupportedOSPlatform {
            get {
                return ResourceManager.GetString("NotSupportedOSPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported PTX architecture.
        /// </summary>
        internal static string NotSupportedPTXArchitecture {
            get {
                return ResourceManager.GetString("NotSupportedPTXArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported target accelerator.
        /// </summary>
        internal static string NotSupportedTargetAccelerator {
            get {
                return ResourceManager.GetString("NotSupportedTargetAccelerator", resourceCulture);
            }
        }
    }
}
