//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILGPU.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuntimeErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuntimeErrorMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ILGPU.Resources.RuntimeErrorMessages", typeof(RuntimeErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot enable peer access to an accelerator of a different kind.
        /// </summary>
        internal static string CannotEnablePeerAccessToDifferentAcceleratorKind {
            get {
                return ResourceManager.GetString("CannotEnablePeerAccessToDifferentAcceleratorKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error-description string could not be resolved.
        /// </summary>
        internal static string CannotResolveErrorString {
            get {
                return ResourceManager.GetString("CannotResolveErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cuda is not supported on this platform.
        /// </summary>
        internal static string CudaNotSupported {
            get {
                return ResourceManager.GetString("CudaNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid custom group size &gt; 0 in a grouped-index scenario.
        /// </summary>
        internal static string InvalidCustomGroupSize {
            get {
                return ResourceManager.GetString("InvalidCustomGroupSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid grid dimension.
        /// </summary>
        internal static string InvalidGridDimension {
            get {
                return ResourceManager.GetString("InvalidGridDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid group dimension.
        /// </summary>
        internal static string InvalidGroupDimension {
            get {
                return ResourceManager.GetString("InvalidGroupDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The given kernel specialization is not compatible with the defined group size..
        /// </summary>
        internal static string InvalidKernelSpecializationGroupSize {
            get {
                return ResourceManager.GetString("InvalidKernelSpecializationGroupSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of provided arguments does not match the required length.
        /// </summary>
        internal static string InvalidNumberOfUniformArgs {
            get {
                return ResourceManager.GetString("InvalidNumberOfUniformArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shared-memory size cannot be &lt; 0.
        /// </summary>
        internal static string InvalidSharedMemorySize {
            get {
                return ResourceManager.GetString("InvalidSharedMemorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not supported explicitly-grouped kernel.
        /// </summary>
        internal static string NotSupportedExplicitlyGroupedKernel {
            get {
                return ResourceManager.GetString("NotSupportedExplicitlyGroupedKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not supported index type.
        /// </summary>
        internal static string NotSupportedIndexType {
            get {
                return ResourceManager.GetString("NotSupportedIndexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not supported kernel.
        /// </summary>
        internal static string NotSupportedKernel {
            get {
                return ResourceManager.GetString("NotSupportedKernel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The given kernel specialization is not compatible with the current accelerator..
        /// </summary>
        internal static string NotSupportedKernelSpecialization {
            get {
                return ResourceManager.GetString("NotSupportedKernelSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type type &apos;{0}&apos; is not blittable.
        /// </summary>
        internal static string NotSupportedNonBlittableType {
            get {
                return ResourceManager.GetString("NotSupportedNonBlittableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not supported PTX architecture.
        /// </summary>
        internal static string NotSupportedPTXArchitecture {
            get {
                return ResourceManager.GetString("NotSupportedPTXArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not supported target accelerator.
        /// </summary>
        internal static string NotSupportedTargetAccelerator {
            get {
                return ResourceManager.GetString("NotSupportedTargetAccelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not supported total group size. The total group size must be &lt;= the number of available threads ({0}).
        /// </summary>
        internal static string NotSupportedTotalGroupSize {
            get {
                return ResourceManager.GetString("NotSupportedTotalGroupSize", resourceCulture);
            }
        }
    }
}
