<Project>
  <!-- Library Project Configuration -->
  <PropertyGroup>
    <LibraryTargetFrameworks>net10.0</LibraryTargetFrameworks>
    <LibraryLatestTargetFramework>$(LibraryTargetFrameworks)</LibraryLatestTargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LibraryVersionPrefix>2.0.0-beta1</LibraryVersionPrefix>
    <LibraryAssemblyVersion>2.0.0.0</LibraryAssemblyVersion>
    <LibraryFileVersion>2.0.0.0</LibraryFileVersion>
    <LibraryPackageValidationBaselineVersion>1.5.2</LibraryPackageValidationBaselineVersion>
  </PropertyGroup>

  <!-- Unit Test Project Configuration -->
  <PropertyGroup>
    <LibraryUnitTestTargetFrameworks>net10.0</LibraryUnitTestTargetFrameworks>
    <LibraryLatestUnitTestTargetFramework>$(LibraryUnitTestTargetFrameworks)</LibraryLatestUnitTestTargetFramework>
  </PropertyGroup>
  <Import Project="..\Tools\CheckStyles\ILGPU.CheckStyles.targets" />
</Project>